### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pierre-x**
I propose the following feature: to be able to upload files from the phone to the shared folder.

### CODE REVIEW

**Comment by parvardegr** [comment]
Hi @pierre-x very great idea,
if you like to done this i can guide you (i can give you merge access after this ✌️), otherwise i will implement it at some point in the future. 
also i will merge this pull request a couple of hours later.

thanks 🙏

**Comment by pierre-x** [comment]
Thank you for your merge.
I'm an embedded firmware developper, not a Node developper, but I'm going to take a look if serve-handler can easily handle file upload.

**Comment by parvardegr** [comment]
> Thank you for your merge. I'm an embedded firmware developper, not a Node developper, but I'm going to take a look if serve-handler can easily handle file upload.
> […](#)

very cool, the code is very simple and i’m sure you can figure it out what happened there,
i think a more simple approach could be:
add new flag —upload to indicate that sharing is in upload mode.
if flag —upload was used, we just provide another server-handler that handles the requests for uploading files (also have a ui for uploading file)

if you can find an npm package that could provide a simple html and backend for uploading files we can use that easily for this purpose without too much efforts

great regards

**Comment by Seven-Y-Q-Guo** [comment]
https://github.com/parvardegr/sharing/pull/25

**Pull request merged**
