### PR TITLE
Moved configuration from main to config.js file

### PR DESCRIPTION
**Pull request by raimonomiar**
I believe it would be good to store the constant in separate file.
I want to move the port to constant as well but why do we have two different ports assigned?

### CODE REVIEW

**Comment by parvardegr** [comment]
Hi @raimonomiar, Thanks for the PR
the intention of `const config` is just to be a placeholder for runtime configuration that get filled with `options` and portfinder in runtime.
so i think looking at it as some configuration that users want to change it often is not a good point of view in this case.
separating it from the `index.js` does not provide an advantage for the end user and us either.
on the other hand it's just a small couple of lines.

@Seven-Y-Q-Guo what's your opinion on this? 

Great Regards

**Comment by Seven-Y-Q-Guo** [comment]
> Hi @raimonomiar, Thanks for the PR the intention of `const config` is just to be a placeholder for runtime configuration that get filled with `options` and portfinder in runtime. so i think looking at it as some configuration that users want to change it often is not a good point of view in this case. separating it from the `index.js` does not provide an advantage for the end user and us either. on the other hand it's just a small couple of lines.
> 
> @Seven-Y-Q-Guo what's your opinion on this?
> 
> Great Regards

I think it's good point, we need to consider how to structure our code with increasing logic.

**Comment by Seven-Y-Q-Guo** [comment]
we should have two mode, one is for Dev, the other is for build.
for now the file is both for dev and build.

**Comment by raimonomiar** [comment]
@parvardegr @Seven-Y-Q-Guo Yes separating into different file doesn't provide advantage for now, but I believe it's still better than having things hardcoded.

**Comment by parvardegr** [comment]
> > Hi @raimonomiar, Thanks for the PR the intention of `const config` is just to be a placeholder for runtime configuration that get filled with `options` and portfinder in runtime. so i think looking at it as some configuration that users want to change it often is not a good point of view in this case. separating it from the `index.js` does not provide an advantage for the end user and us either. on the other hand it's just a small couple of lines.
> > @Seven-Y-Q-Guo what's your opinion on this?
> > Great Regards
> 
> I think it's good point, we need to consider how to structure our code with increasing logic.

Great, you’re right about it, but i think config.js is a pattern and is equal to use something like config.properties in java or other languages, in our case this ‘config variable’ is just a simple variable so we don’t need to overuse ‘options’ it’s more like ‘parsedOptions’ than our application configuration.
and as you can see all the values in it are evaluate and set at runtime.

@Seven-Y-Q-Guo in the end i need you to decide what to do with this PR, if you think it has some value for the project you can accept it 🙏

Great Regards

**Review by Seven-Y-Q-Guo — APPROVED** [review]
looks fine on my side, approved

**Comment by parvardegr** [comment]
> looks fine on my side, approved

very well, you can squash and merge it then.
also i want to mention that although i was not a fan of this PR but i’m fully support your decision 🙏

@raimonomiar great job✌️

**Pull request merged**
